struct NetworkingUrls {
    static let apiBaseUrl = "https://enjaz.alandrin.com/api"
    static let apiSignupUrl = apiBaseUrl + "/sign-up"
    static let apiLoginUrl = apiBaseUrl + "/login"
    static let apiResetPasswordUrl = apiBaseUrl + "/sendcode"
    static let itemImagesUrl = apiBaseUrl + "/image"
    static let apiRequestEmailVerificationCodeUrl = apiBaseUrl + "/sendbasicemail"
    static let apiEmailVerificationUrl = apiBaseUrl + "/verifyemail"
    static let apiBlogArticlesUrl = apiBaseUrl + "/blog?page="
    static let apiBlogVideosUrl = apiBaseUrl + "/video?page="
    static let apiGoalsSuggestionsBankUrl = apiBaseUrl + "/bank"
    static let apiAboutUs = apiBaseUrl + "/about"
    static let apiPrivacyPolicy = apiBaseUrl + "/privacy"
    static let apiMedals = apiBaseUrl + "/medals"
}
